version: 0.2
phases:
  build:
    commands:
      -retry=0 -testSuitePath="Test Suites/Cura Healthcare" -apiKey="9b26b1f9-8b64-4c42-b5d9-1583bf3ae781" -browserType="Chrome" -executionProfile="default" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true -webui.autoUpdateDrivers=true
artifacts:
  files:
    - report/*
reports: #New
  KatalonTestReports: # CodeBuild will create a report group called "KatalonTestReport".
    files: #Store all of the files
      - 'report/JUnit_Report.xml'
